# Generated by Django 2.0.6 on 2019-09-15 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Money',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Tarix')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Məbləğ')),
            ],
            options={
                'verbose_name_plural': 'Money',
            },
        ),
        migrations.CreateModel(
            name='MoneyIn',
            fields=[
                ('money_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='money.Money')),
            ],
            bases=('money.money',),
        ),
        migrations.CreateModel(
            name='MoneyOut',
            fields=[
                ('money_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='money.Money')),
            ],
            bases=('money.money',),
        ),
    ]
