# Generated by Django 2.2.13 on 2021-02-21 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='money',
            name='description',
            field=models.TextField(default=None, max_length=500, verbose_name='Təsvir'),
        ),
        migrations.AlterField(
            model_name='money',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Məbləğ'),
        ),
    ]
