# Generated by Django 2.0.6 on 2019-11-28 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0002_money_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='money',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Məbləğ'),
        ),
    ]
