# Generated by Django 2.2.13 on 2020-07-05 15:40

from django.db import migrations, models
import network.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkHardware',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(default=None, max_length=100)),
                ('code', models.IntegerField(primary_key=True, serialize=False, verbose_name='Kod')),
                ('brand', models.CharField(default=None, max_length=20, verbose_name='Brend')),
                ('model', models.CharField(max_length=50, verbose_name='Model')),
                ('serial_number', models.CharField(default=0, max_length=50, verbose_name='Seriya Nömrəsi')),
                ('category', models.CharField(default=None, max_length=30, verbose_name='Kateqoriya')),
                ('description', models.TextField(default=None, max_length=500, verbose_name='Təsvir')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Alış qiməti')),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Satış qiyməti')),
                ('quantity', models.IntegerField(default=1, verbose_name='Ədəd')),
                ('image', models.FileField(blank=True, default=None, upload_to=network.models.save_directory_path, verbose_name='Şəkil')),
                ('sold', models.BooleanField(default=False, verbose_name='Satılıb')),
                ('inventory', models.BooleanField(default=False, verbose_name='Inventar')),
            ],
            options={
                'verbose_name_plural': 'Şəbəkə avadanlıqları',
            },
        ),
    ]
