# Generated by Django 2.2.13 on 2021-09-12 12:26

from django.db import migrations, models
import network.models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='networkhardware',
            options={'verbose_name_plural': 'Verbose name'},
        ),
        migrations.AlterField(
            model_name='networkhardware',
            name='brand',
            field=models.CharField(default=None, max_length=20, verbose_name='Brand'),
        ),
        migrations.AlterField(
            model_name='networkhardware',
            name='category',
            field=models.CharField(default=None, max_length=30, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='networkhardware',
            name='code',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='networkhardware',
            name='description',
            field=models.TextField(default=None, max_length=500, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='networkhardware',
            name='image',
            field=models.FileField(blank=True, default=None, upload_to=network.models.save_directory_path, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='networkhardware',
            name='inventory',
            field=models.BooleanField(default=False, verbose_name='Inventory'),
        ),
        migrations.AlterField(
            model_name='networkhardware',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Purchase price'),
        ),
        migrations.AlterField(
            model_name='networkhardware',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='networkhardware',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Selling pricei'),
        ),
        migrations.AlterField(
            model_name='networkhardware',
            name='serial_number',
            field=models.CharField(default=0, max_length=50, verbose_name='Serial Number'),
        ),
        migrations.AlterField(
            model_name='networkhardware',
            name='sold',
            field=models.BooleanField(default=False, verbose_name='Sold'),
        ),
    ]
